# Projet_GL/Premiers/Src/Makefile : pour les nombres premiers

USES =

OBJECTS = premiers

LEXICO =
LEXFLAGS =

SYNTAX =
YACCFLAGS =

TESTS = 

ifndef GL_GLOBAL
GL_GLOBAL = /usr/local/GL/Global
endif

include $(GL_GLOBAL)/init.make
