# Outils/Src/Makefile : pour les outils
# Auteurs : gl16

USES =

OBJECTS = test_outils demande

LEXICO =
LEXFLAGS =

SYNTAX =
YACCFLAGS =

TESTS =

ifndef GL_GLOBAL
GL_GLOBAL = /usr/local/GL/Global
endif

include $(GL_GLOBAL)/init.make
