# Gencode/Src/Makefile : pour la passe de generation de code
#                        et l'executable du compilateur
# Auteurs : gl16

USES = Outils Syntaxe Verif Gencode

OBJECTS = decac

LEXICO =
LEXFLAGS =

SYNTAX =
YACCFLAGS =

TESTS = lanceurDecac.sh

ifndef GL_GLOBAL
GL_GLOBAL = /usr/local/GL/Global/
endif

include $(GL_GLOBAL)/init.make
