# Verif/Src/Makefile : pour la passe de verifications contextuelles
# Auteurs : gl16

USES = Outils Syntaxe

OBJECTS = test_symb test_verif test_erreurs

LEXICO =
LEXFLAGS =

SYNTAX =
YACCFLAGS =

TESTS = lanceurVerif.sh

ifndef GL_GLOBAL
GL_GLOBAL = /usr/local/GL/Global
endif

include $(GL_GLOBAL)/init.make
