# Calc/Src/Makefile : pour la calculette

USES =

OBJECTS = calc

LEXICO = lexico.l
LEXFLAGS = -I

SYNTAX = syntax.y
YACCFLAGS =

TESTS =

ifndef GL_GLOBAL
GL_GLOBAL = /usr/local/GL/Global
endif

include $(GL_GLOBAL)/init.make
