# Syntaxe/Src/Makefile : pour l'analyseur syntaxique
# Auteurs : gl16


USES = Outils

OBJECTS = test_lex test_synt
LEXICO = lexical.l
LEXFLAGS =

SYNTAX = syntaxe.y
YACCFLAGS =

TESTS = lanceurSyntaxe.sh

ifndef GL_GLOBAL
GL_GLOBAL = /usr/local/GL/Global
endif

include $(GL_GLOBAL)/init.make
