# Gencode/Src/Makefile : pour la passe de generation de code
# Auteurs : gl16

USES = Outils Syntaxe Verif

OBJECTS = test_gencode

LEXICO =
LEXFLAGS =

SYNTAX =
YACCFLAGS =

TESTS = lanceurGencode.sh

ifndef GL_GLOBAL
GL_GLOBAL = /usr/local/GL/Global/
endif

include $(GL_GLOBAL)/init.make
